FROM node

#Establecer el directorio de trabajo 
WORKDIR /app

#Copiar el package.json y package-lock.json
COPY package*.json ./

#Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Expone el puerto
EXPOSE 5000

# Comando para ejecutar la app
CMD ["npm","start"]